### ISSUE TITLE
Styling options

### ISSUE THREAD

**Issue by marlonbosse** [Imgkl/anim_search_bar#3]
Thanks for this awesome widget,

currently I have some issues in regards to the customization that is being offered.

- Hardcoded height
- TextStyle can 't be set
- Color of icon can't be set since you expect `IconData` instead of `Icon`
- How to close the search bar again with suffixTap? 
- autofocus on the textfield would be helpful

**Comment by Imgkl** [comment]
@marlonbosse  Thanks for trying out this package. Really great ideas, I'll update the package with your requests soon.

**Comment by Imgkl** [comment]
@marlonbosse  I've added these features to the version `1.0.1`

 - Adding TextStyle - `style` property.
 - AutoFocus of text field, when the search bar is expanded keyboard shows automatically and when the search bar is closed, the keyboard is auto-dismissed (`autoFocus = true`).
 - Close the search bar on suffixTap (`closeOnSuffixTap = true`).
 - Prefix and suffix are now Icons, not IconData, to allow more granular customisations.

Please upgrade to the latest package: **`anim_search_bar: ^1.0.1`**

Need more clarity on what you mean by "Hardcoded height".

**Comment by marlonbosse** [comment]
@Imgkl thanks a lot!

In regards to "hardcoded height": I'm pretty new to flutter so I'm not sure but how do I specify a height for the search_bar?

**Comment by Imgkl** [comment]
@marlonbosse The height of the search bar is the same as the default text field. I intend to keep the default height because customising this may lead to weird text clipping issue on smaller devices. If this feature is crucial to many people, I'll work on it, until then I can't say this is on my roadmap. 


Thank you once again for using this package and your valuable suggestions to make this package better. I'm closing this issue, feel free to open it in future, if there's any need for it.

**Comment by faisalmushtaq007** [comment]
@Imgkl is there a way to decrease the size of it?
